package com.stability.martrix.service.parser;

import com.stability.martrix.entity.AArch64Tombstone;
import com.stability.martrix.entity.TroubleEntity;
import com.stability.martrix.entity.register.AArch64RegisterDumpInfo;
import com.stability.martrix.enums.CPUArchitecture;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * OpenHarmony 日志文件解析器
 *
 * 解析 OpenHarmony 系统的崩溃日志文件
 * 支持 ARM32 格式日志转换为 ARM64 解析结果
 */
@Component
public class OpenHarmonyLogFileParser implements FileParserStrategy {

    private static final Logger logger = Logger.getLogger(OpenHarmonyLogFileParser.class.getName());

    private static final String[] OPENHARMONY_MARKERS = {
        "Generated by HiviewDFX@OpenHarmony",
        "HiviewDFX",
        "OpenHarmony"
    };

    // 解析模式
    private static final Pattern PID_PATTERN = Pattern.compile("Pid:(\\d+)");
    private static final Pattern UID_PATTERN = Pattern.compile("Uid:(\\d+)");
    private static final Pattern TID_PATTERN = Pattern.compile("Tid:(\\d+)");
    private static final Pattern PROCESS_NAME_PATTERN = Pattern.compile("Process name:(\\S+)");
    private static final Pattern MODULE_NAME_PATTERN = Pattern.compile("Module name:(\\S+)");
    private static final Pattern TIMESTAMP_PATTERN = Pattern.compile("Timestamp:(\\d{4}-\\d{2}-\\d{2}[T\\s]\\d{2}:\\d{2}:\\d{2})");
    private static final Pattern SIGNAL_PATTERN = Pattern.compile("Reason:Signal:([A-Z]+)\\(([^)]+)\\)@0x([0-9a-fA-F]+)");
    private static final Pattern FAULT_THREAD_PATTERN = Pattern.compile("Tid:(\\d+),\\s*Name:(\\S+)");
    private static final Pattern STACK_FRAME_PATTERN = Pattern.compile("#(\\d+)\\s+pc\\s+([0-9a-fA-F]+)\\s+(\\S+)\\s*\\(([^)]*)\\)(.*)");
    private static final Pattern REGISTER_PATTERN = Pattern.compile("([a-z0-9]+):([0-9a-fA-F]+)");
    private static final Pattern MAPS_PATTERN = Pattern.compile("([0-9a-fA-F]+)-([0-9a-fA-F]+)\\s+([rwxps-]+)\\s+([0-9a-fA-F]+)\\s+(\\S+)");

    @Override
    public String getPlatformName() {
        return "OpenHarmony";
    }

    @Override
    public int getPriority() {
        return 20;
    }

    @Override
    public boolean canParse(List<String> lines) {
        if (lines == null || lines.isEmpty()) {
            return false;
        }

        int checkLines = Math.min(50, lines.size());
        for (int i = 0; i < checkLines; i++) {
            String line = lines.get(i);
            for (String marker : OPENHARMONY_MARKERS) {
                if (line.contains(marker)) {
                    return true;
                }
            }
        }
        return false;
    }

    @Override
    public TroubleEntity parse(List<String> lines) {
        if (lines == null || lines.isEmpty()) {
            return null;
        }

        AArch64Tombstone tombstone = new AArch64Tombstone();
        tombstone.setCpuArchitecture(CPUArchitecture.ARM64);

        Map<String, String> registers = new HashMap<>();
        List<AArch64Tombstone.StackDumpInfo.StackFrame> stackFrames = new ArrayList<>();
        List<AArch64Tombstone.MapsInfo> mapsList = new ArrayList<>();

        boolean inRegisters = false;
        boolean inStackTrace = false;
        boolean inMaps = false;
        boolean inFaultThread = false;

        String threadName = null;
        Integer tid = null;

        for (int i = 0; i < lines.size(); i++) {
            String line = lines.get(i).trim();

            // 解析基本信息
            if (line.startsWith("Pid:")) {
                Matcher m = PID_PATTERN.matcher(line);
                if (m.find()) {
                    tombstone.setPid(Integer.parseInt(m.group(1)));
                }
            } else if (line.startsWith("Uid:")) {
                // Uid信息暂时不存储在当前实体中
            } else if (line.startsWith("Process name:")) {
                Matcher m = PROCESS_NAME_PATTERN.matcher(line);
                if (m.find()) {
                    tombstone.setProcessName(m.group(1));
                }
            } else if (line.startsWith("Module name:")) {
                // Module name 暂时不存储在当前实体中
            } else if (line.contains("Build info:")) {
                // 解析 Build info 作为 version（使用contains处理行首可能有空格的情况）
                int index = line.indexOf("Build info:");
                String version = line.substring(index + "Build info:".length()).trim();
                tombstone.setVersion(version);
            } else if (line.startsWith("Timestamp:")) {
                // Timestamp 暂时不存储在当前实体中
            } else if (line.startsWith("Reason:")) {
                // 解析Signal信息
                parseSignal(line, tombstone);
            } else if (line.startsWith("Fault thread info:") || line.startsWith("FaultThreadInfo:")) {
                inFaultThread = true;
            } else if (line.startsWith("Tid:") && inFaultThread) {
                Matcher m = FAULT_THREAD_PATTERN.matcher(line);
                if (m.find()) {
                    tid = Integer.parseInt(m.group(1));
                    threadName = m.group(2);
                    tombstone.setFirstTid(tid);
                }
            } else if (line.startsWith("#") && line.contains("pc ") && !line.startsWith("Registers:")) {
                // 解析堆栈帧
                AArch64Tombstone.StackDumpInfo.StackFrame frame = parseStackFrame(line);
                if (frame != null) {
                    stackFrames.add(frame);
                }
            } else if (line.startsWith("Registers:")) {
                inRegisters = true;
                inStackTrace = false;
                inMaps = false;
            } else if (inRegisters && !line.isEmpty() && !line.startsWith("Memory") && !line.startsWith("Registers")) {
                // 解析寄存器
                Matcher m = REGISTER_PATTERN.matcher(line);
                while (m.find()) {
                    registers.put(m.group(1), m.group(2));
                }
                if (line.startsWith("cpsr:") || (registers.size() >= 11 && !line.contains(":"))) {
                    inRegisters = false;
                }
            } else if (line.startsWith("Maps:")) {
                inMaps = true;
                inRegisters = false;
                inStackTrace = false;
            } else if (inMaps && line.matches("[0-9a-fA-F]+-[0-9a-fA-F]+.*")) {
                // 解析Maps
                AArch64Tombstone.MapsInfo mapsInfo = parseMaps(line);
                if (mapsInfo != null) {
                    mapsList.add(mapsInfo);
                }
            } else if (line.startsWith("OpenFiles:") || line.startsWith("HiLog:")) {
                inMaps = false;
            }
        }

        // 设置堆栈信息
        if (!stackFrames.isEmpty()) {
            AArch64Tombstone.StackDumpInfo stackDumpInfo = new AArch64Tombstone.StackDumpInfo();
            stackDumpInfo.setStackFrames(stackFrames);
            tombstone.setStackDumpInfo(stackDumpInfo);
        }

        // 设置Maps信息
        if (!mapsList.isEmpty()) {
            tombstone.setMapsInfoList(mapsList);
        }

        // 将ARM32寄存器转换为ARM64格式
        AArch64RegisterDumpInfo registerDumpInfo = convertRegisters(registers);
        tombstone.setRegisterDumpInfo(registerDumpInfo);

        // 设置特殊寄存器
        if (registerDumpInfo != null) {
            AArch64Tombstone.SpecialRegisterInfo specialRegister = new AArch64Tombstone.SpecialRegisterInfo(
                registerDumpInfo.getX30(),
                registerDumpInfo.getSp(),
                registerDumpInfo.getPc(),
                null
            );
            tombstone.setSpecialRegisterInfo(specialRegister);
        }

        logger.info("Parsed OpenHarmony log: pid=" + tombstone.getPid() +
                    ", signal=" + (tombstone.getSignalInfo() != null ? tombstone.getSignalInfo().getSigNumber() : "unknown") +
                    ", stackFrames=" + stackFrames.size());

        return tombstone;
    }

    private void parseSignal(String line, AArch64Tombstone tombstone) {
        Matcher m = SIGNAL_PATTERN.matcher(line);
        if (m.find()) {
            String signalName = m.group(1);
            String signalInfo = m.group(2);
            String faultAddrStr = m.group(3);

            int signalNumber = getSignalNumber(signalName);
            Long faultAddress = null;
            try {
                faultAddress = Long.parseLong(faultAddrStr, 16);
            } catch (NumberFormatException e) {
                // ignore
            }

            AArch64Tombstone.SignalInfo signalInfoObj = new AArch64Tombstone.SignalInfo(
                signalNumber,
                signalName + "(" + signalInfo + ")",
                line,
                faultAddress,
                null,
                null
            );
            tombstone.setSignalInfo(signalInfoObj);
        }
    }

    private int getSignalNumber(String signalName) {
        switch (signalName) {
            case "SIGSEGV": return 11;
            case "SIGABRT": return 6;
            case "SIGBUS": return 7;
            case "SIGFPE": return 8;
            case "SIGILL": return 4;
            case "SIGPIPE": return 13;
            default: return 0;
        }
    }

    private AArch64Tombstone.StackDumpInfo.StackFrame parseStackFrame(String line) {
        // 格式: #00 pc 000ef8d4 /system/lib/ld-musl-arm.so.1(__isoc99_vfwscanf+52)(acbcd8a38a05aef9b405c54d21ad6ad5)
        Pattern pattern = Pattern.compile("#(\\d+)\\s+pc\\s+([0-9a-fA-F]+)\\s+(\\S+)\\s*(?:\\(([^)]*)\\))?(?:\\(([^)]*)\\))?");
        Matcher m = pattern.matcher(line);
        if (m.find()) {
            int index = Integer.parseInt(m.group(1));
            String addressStr = m.group(2);
            String library = m.group(3);
            String symbolInfo = m.group(4);
            String buildId = m.group(5);

            Long address = null;
            try {
                address = Long.parseLong(addressStr, 16);
            } catch (NumberFormatException e) {
                // ignore
            }

            String symbol = null;
            Long offset = null;
            if (symbolInfo != null && symbolInfo.contains("+")) {
                String[] parts = symbolInfo.split("\\+");
                symbol = parts[0];
                try {
                    offset = Long.parseLong(parts[1], 16);
                } catch (NumberFormatException e) {
                    // ignore
                }
            } else if (symbolInfo != null) {
                symbol = symbolInfo;
            }

            AArch64Tombstone.StackDumpInfo.StackFrame frame = new AArch64Tombstone.StackDumpInfo.StackFrame(
                offset,
                symbol,
                library,
                AArch64Tombstone.StackDumpInfo.StackFrame.AddressType.ABSOLUTE,
                address,
                index,
                buildId
            );
            return frame;
        }
        return null;
    }

    private AArch64RegisterDumpInfo convertRegisters(Map<String, String> arm32Registers) {
        AArch64RegisterDumpInfo info = new AArch64RegisterDumpInfo();

        // ARM32 r0-r10 对应 ARM64 x0-x10
        for (int i = 0; i <= 10; i++) {
            String regName = "r" + i;
            String value = arm32Registers.get(regName);
            if (value != null) {
                try {
                    long val = Long.parseLong(value, 16);
                    switch (i) {
                        case 0: info.setX0(val); break;
                        case 1: info.setX1(val); break;
                        case 2: info.setX2(val); break;
                        case 3: info.setX3(val); break;
                        case 4: info.setX4(val); break;
                        case 5: info.setX5(val); break;
                        case 6: info.setX6(val); break;
                        case 7: info.setX7(val); break;
                        case 8: info.setX8(val); break;
                        case 9: info.setX9(val); break;
                        case 10: info.setX10(val); break;
                    }
                } catch (NumberFormatException e) {
                    // ignore
                }
            }
        }

        // ARM32 fp (r11) -> x29
        String fpValue = arm32Registers.get("fp");
        if (fpValue != null) {
            try {
                info.setX29(Long.parseLong(fpValue, 16));
            } catch (NumberFormatException e) {
                // ignore
            }
        }

        // ARM32 ip (r12) -> x16
        String ipValue = arm32Registers.get("ip");
        if (ipValue != null) {
            try {
                info.setX16(Long.parseLong(ipValue, 16));
            } catch (NumberFormatException e) {
                // ignore
            }
        }

        // ARM32 sp -> sp
        String spValue = arm32Registers.get("sp");
        if (spValue != null) {
            try {
                info.setSp(Long.parseLong(spValue, 16));
            } catch (NumberFormatException e) {
                // ignore
            }
        }

        // ARM32 lr -> x30
        String lrValue = arm32Registers.get("lr");
        if (lrValue != null) {
            try {
                info.setX30(Long.parseLong(lrValue, 16));
            } catch (NumberFormatException e) {
                // ignore
            }
        }

        // ARM32 pc -> pc
        String pcValue = arm32Registers.get("pc");
        if (pcValue != null) {
            try {
                info.setPc(Long.parseLong(pcValue, 16));
            } catch (NumberFormatException e) {
                // ignore
            }
        }

        return info;
    }

    private AArch64Tombstone.MapsInfo parseMaps(String line) {
        // 格式: bc2000-bc5000 r--p 00000000 /data/local/tmp/libc-test/vfwscanf
        Matcher m = MAPS_PATTERN.matcher(line);
        if (m.find()) {
            try {
                Long start = Long.parseLong(m.group(1), 16);
                Long end = Long.parseLong(m.group(2), 16);
                String permission = m.group(3);
                String name = m.group(5);
                return new AArch64Tombstone.MapsInfo(start, end, permission, name);
            } catch (NumberFormatException e) {
                // ignore
            }
        }
        return null;
    }

    @Override
    public boolean isValid(TroubleEntity entity) {
        return entity != null && entity.getPid() != null;
    }
}
