package com.stability.martrix.service.parser;

import com.stability.martrix.entity.AArch64Tombstone;
import com.stability.martrix.entity.TroubleEntity;
import com.stability.martrix.entity.register.AArch64RegisterDumpInfo;
import com.stability.martrix.enums.CPUArchitecture;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * OpenHarmony 日志文件解析器
 *
 * 解析 OpenHarmony 系统的崩溃日志文件
 * 支持 ARM32 格式日志转换为 ARM64 解析结果
 */
@Component
public class OpenHarmonyLogFileParser implements FileParserStrategy {

    private static final Logger logger = Logger.getLogger(OpenHarmonyLogFileParser.class.getName());

    private static final String[] OPENHARMONY_MARKERS = {
        "Generated by HiviewDFX@OpenHarmony",
        "HiviewDFX",
        "OpenHarmony"
    };

    // 解析模式
    private static final Pattern PID_PATTERN = Pattern.compile("Pid:(\\d+)");
    private static final Pattern UID_PATTERN = Pattern.compile("Uid:(\\d+)");
    private static final Pattern TID_PATTERN = Pattern.compile("Tid:(\\d+)");
    private static final Pattern PROCESS_NAME_PATTERN = Pattern.compile("Process name:(\\S+)");
    private static final Pattern MODULE_NAME_PATTERN = Pattern.compile("Module name:(\\S+)");
    private static final Pattern TIMESTAMP_PATTERN = Pattern.compile("Timestamp:(\\d{4}-\\d{2}-\\d{2}[T\\s]\\d{2}:\\d{2}:\\d{2})");
    private static final Pattern SIGNAL_PATTERN = Pattern.compile("Reason:Signal:([A-Z]+)\\(([^)]+)\\)@0x([0-9a-fA-F]+)");
    private static final Pattern FAULT_THREAD_PATTERN = Pattern.compile("Tid:(\\d+),\\s*Name:(\\S+)");
    private static final Pattern STACK_FRAME_PATTERN = Pattern.compile("#(\\d+)\\s+pc\\s+([0-9a-fA-F]+)\\s+(\\S+)\\s*\\(([^)]*)\\)(.*)");
    private static final Pattern REGISTER_PATTERN = Pattern.compile("([a-z0-9]+):([0-9a-fA-F]+)");
    private static final Pattern MAPS_PATTERN = Pattern.compile("([0-9a-fA-F]+)-([0-9a-fA-F]+)\\s+([rwxps-]+)\\s+([0-9a-fA-F]+)\\s+(\\S+)");

    @Override
    public String getPlatformName() {
        return "OpenHarmony";
    }

    @Override
    public int getPriority() {
        return 20;
    }

    @Override
    public boolean canParse(List<String> lines) {
        if (lines == null || lines.isEmpty()) {
            return false;
        }

        int checkLines = Math.min(50, lines.size());
        for (int i = 0; i < checkLines; i++) {
            String line = lines.get(i);
            for (String marker : OPENHARMONY_MARKERS) {
                if (line.contains(marker)) {
                    return true;
                }
            }
        }
        return false;
    }

    @Override
    public TroubleEntity parse(List<String> lines) {
        if (lines == null || lines.isEmpty()) {
            return null;
        }

        AArch64Tombstone tombstone = new AArch64Tombstone();
        tombstone.setCpuArchitecture(CPUArchitecture.ARM64);

        Map<String, String> registers = new HashMap<>();
        List<AArch64Tombstone.StackDumpInfo.StackFrame> stackFrames = new ArrayList<>();
        List<AArch64Tombstone.StackDumpInfo.StackFrame> submitterStackFrames = new ArrayList<>();  // 父线程堆栈
        List<AArch64Tombstone.MapsInfo> mapsList = new ArrayList<>();

        boolean inRegisters = false;
        boolean inStackTrace = false;
        boolean inMaps = false;
        boolean inFaultThread = false;  // 是否正在解析崩溃线程的堆栈
        boolean parsingSubmitterThread = false;  // 是否正在解析父线程（Submitter）的堆栈

        String threadName = null;
        Integer tid = null;
        Integer submitterTid = null;  // 父线程的TID

        for (int i = 0; i < lines.size(); i++) {
            String line = lines.get(i).trim();

            // 解析基本信息
            if (line.startsWith("Pid:")) {
                Matcher m = PID_PATTERN.matcher(line);
                if (m.find()) {
                    tombstone.setPid(Integer.parseInt(m.group(1)));
                }
            } else if (line.startsWith("Uid:")) {
                // Uid信息暂时不存储在当前实体中
            } else if (line.startsWith("Process name:")) {
                Matcher m = PROCESS_NAME_PATTERN.matcher(line);
                if (m.find()) {
                    tombstone.setProcessName(m.group(1));
                }
            } else if (line.startsWith("Module name:")) {
                // Module name 暂时不存储在当前实体中
            } else if (line.contains("Build info:")) {
                // 解析 Build info 作为 version（使用contains处理行首可能有空格的情况）
                int index = line.indexOf("Build info:");
                String version = line.substring(index + "Build info:".length()).trim();
                tombstone.setVersion(version);
            } else if (line.startsWith("Timestamp:")) {
                // Timestamp 暂时不存储在当前实体中
            } else if (line.startsWith("Reason:")) {
                // 解析Signal信息
                parseSignal(line, tombstone);
            } else if (line.startsWith("Tid:")) {
                Matcher m = FAULT_THREAD_PATTERN.matcher(line);
                if (m.find()) {
                    tid = Integer.parseInt(m.group(1));
                    threadName = m.group(2);
                    // 第一次遇到Tid时设置为崩溃线程，后续遇到则说明是其他线程
                    if (!inFaultThread) {
                        inFaultThread = true;
                        tombstone.setFirstTid(tid);
                    } else {
                        // 再次遇到Tid，说明崩溃线程解析完成
                        inFaultThread = false;
                        // 也要将父线程的解析流程结束
                        parsingSubmitterThread = false;
                    }
                }
            } else if (line.contains("====SubmitterStacktrace====")) {
                // 遇到父线程标记，开始解析父线程堆栈
                parsingSubmitterThread = true;
                // 这里也需要将崩溃线程的解析置为false
                inFaultThread = false;
            } else if (parsingSubmitterThread && line.startsWith("Tid:")) {
                // 解析父线程的Tid
                Matcher m = TID_PATTERN.matcher(line);
                if (m.find()) {
                    submitterTid = Integer.parseInt(m.group(1));
                }
            } else if (parsingSubmitterThread && line.startsWith("#") && line.contains(" at ") && !line.startsWith("Registers:")) {
                // 解析父线程高级语言堆栈帧
                AArch64Tombstone.StackDumpInfo.StackFrame frame = parseHighLevelStackFrame(line);
                if (frame != null) {
                    submitterStackFrames.add(frame);
                }
            } else if (parsingSubmitterThread && line.startsWith("#") && line.contains("pc ") && !line.startsWith("Registers:")) {
                // 解析父线程native堆栈帧
                AArch64Tombstone.StackDumpInfo.StackFrame frame = parseStackFrame(line);
                if (frame != null) {
                    submitterStackFrames.add(frame);
                }
            } else if (inFaultThread && line.startsWith("#") && line.contains(" at ") && !line.startsWith("Registers:")) {
                // 解析崩溃线程高级语言堆栈帧
                AArch64Tombstone.StackDumpInfo.StackFrame frame = parseHighLevelStackFrame(line);
                if (frame != null) {
                    stackFrames.add(frame);
                }
            } else if (inFaultThread && line.startsWith("#") && line.contains("pc ") && !line.startsWith("Registers:")) {
                // 解析崩溃线程native堆栈帧
                AArch64Tombstone.StackDumpInfo.StackFrame frame = parseStackFrame(line);
                if (frame != null) {
                    stackFrames.add(frame);
                }
            } else if (line.startsWith("Registers:")) {
                inRegisters = true;
                inStackTrace = false;
                inMaps = false;
            } else if (inRegisters && !line.isEmpty() && !line.startsWith("Memory") && !line.startsWith("Registers")) {
                // 解析寄存器
                Matcher m = REGISTER_PATTERN.matcher(line);
                while (m.find()) {
                    registers.put(m.group(1), m.group(2));
                }
                // 寄存器解析结束条件：遇到 pstate (ARM64) 结尾
                if (line.contains("pstate:")) {
                    inRegisters = false;
                }
            } else if (line.startsWith("Maps:")) {
                inMaps = true;
                inRegisters = false;
                inStackTrace = false;
            } else if (inMaps && line.matches("[0-9a-fA-F]+-[0-9a-fA-F]+.*")) {
                // 解析Maps
                AArch64Tombstone.MapsInfo mapsInfo = parseMaps(line);
                if (mapsInfo != null) {
                    mapsList.add(mapsInfo);
                }
            } else if (line.startsWith("OpenFiles:") || line.startsWith("HiLog:")) {
                inMaps = false;
            }
        }

        // 设置堆栈信息
        if (!stackFrames.isEmpty()) {
            AArch64Tombstone.StackDumpInfo stackDumpInfo = new AArch64Tombstone.StackDumpInfo();
            stackDumpInfo.setStackFrames(stackFrames);
            tombstone.setStackDumpInfo(stackDumpInfo);
        }

        // 设置父线程（Submitter）堆栈信息
        if (!submitterStackFrames.isEmpty()) {
            AArch64Tombstone.StackDumpInfo submitterStackDumpInfo = new AArch64Tombstone.StackDumpInfo();
            submitterStackDumpInfo.setStackFrames(submitterStackFrames);
            tombstone.setSubmitterStackDumpInfo(submitterStackDumpInfo);
        }

        // 设置Maps信息
        if (!mapsList.isEmpty()) {
            tombstone.setMapsInfoList(mapsList);
        }

        // 将ARM32寄存器转换为ARM64格式
        AArch64RegisterDumpInfo registerDumpInfo = convertRegisters(registers);
        tombstone.setRegisterDumpInfo(registerDumpInfo);

        // 设置特殊寄存器
        if (registerDumpInfo != null) {
            AArch64Tombstone.SpecialRegisterInfo specialRegister = new AArch64Tombstone.SpecialRegisterInfo(
                registerDumpInfo.getX30(),
                registerDumpInfo.getSp(),
                registerDumpInfo.getPc(),
                null
            );
            tombstone.setSpecialRegisterInfo(specialRegister);
        }

        logger.info("Parsed OpenHarmony log: pid=" + tombstone.getPid() +
                    ", signal=" + (tombstone.getSignalInfo() != null ? tombstone.getSignalInfo().getSigNumber() : "unknown") +
                    ", stackFrames=" + stackFrames.size());

        return tombstone;
    }

    private void parseSignal(String line, AArch64Tombstone tombstone) {
        Matcher m = SIGNAL_PATTERN.matcher(line);
        if (m.find()) {
            String signalName = m.group(1);
            String signalInfo = m.group(2);
            String faultAddrStr = m.group(3);

            int signalNumber = getSignalNumber(signalName);
            Long faultAddress = null;
            try {
                faultAddress = Long.parseLong(faultAddrStr, 16);
            } catch (NumberFormatException e) {
                // ignore
            }

            AArch64Tombstone.SignalInfo signalInfoObj = new AArch64Tombstone.SignalInfo(
                signalNumber,
                signalName + "(" + signalInfo + ")",
                line,
                faultAddress,
                null,
                null
            );
            tombstone.setSignalInfo(signalInfoObj);
        }
    }

    private int getSignalNumber(String signalName) {
        switch (signalName) {
            // 标准POSIX信号
            case "SIGHUP": return 1;    // 挂起
            case "SIGINT": return 2;    // 中断
            case "SIGQUIT": return 3;  // 退出
            case "SIGILL": return 4;   // 非法指令
            case "SIGTRAP": return 5;  // 陷阱
            case "SIGABRT": return 6;  // 中止
            case "SIGBUS": return 7;    // 总线错误
            case "SIGFPE": return 8;    // 浮点异常
            case "SIGKILL": return 9;  // 杀死
            case "SIGUSR1": return 10;  // 用户自定义信号1
            case "SIGSEGV": return 11; // 段错误
            case "SIGUSR2": return 12;  // 用户自定义信号2
            case "SIGPIPE": return 13;  // 管道破裂
            case "SIGALRM": return 14;  // 闹钟
            case "SIGTERM": return 15;  // 终止
            case "SIGSTKFLT": return 16; // 协处理器栈错误
            case "SIGCHLD": return 17;  // 子进程终止
            case "SIGCONT": return 18;  // 继续执行
            case "SIGSTOP": return 19;  // 停止
            case "SIGTSTP": return 20;  // 终端停止信号
            case "SIGTTIN": return 21;  // 后台读
            case "SIGTTOU": return 22;  // 后台写
            case "SIGURG": return 23;   // 紧急插座事件
            case "SIGXCPU": return 24;  // CPU时间超限
            case "SIGXFSZ": return 25;  // 文件大小超限
            case "SIGVTALRM": return 26; // 虚拟闹钟
            case "SIGPROF": return 27;   // profiling定时器届满
            case "SIGWINCH": return 28; // 窗口大小改变
            case "SIGIO": return 29;    // I/O现在可能
            case "SIGPWR": return 30;   // 电源失效
            case "SIGSYS": return 31;   // 非法系统调用
            default: return 0;
        }
    }

    /**
     * 解析高级语言堆栈帧（如 TypeScript/ArkTS）
     * 格式: #07 at anonymous (xxx.ts:41:15) 或 #07 at d94 (xxx.ts:55:10)
     */
    private AArch64Tombstone.StackDumpInfo.StackFrame parseHighLevelStackFrame(String line) {
        // 格式: #07 at symbol (file:line:col) 或 #07 at address (file:line:col)
        // 示例: #00 at hello (index.ets:24:9)
        //       #01 at foo (index.ets:10:5)
        Pattern pattern = Pattern.compile("#(\\d+)\\s+at\\s+(\\S+)\\s*\\(([^)]+):(\\d+):(\\d+)\\)");
        Matcher m = pattern.matcher(line);
        if (m.find()) {
            int index = Integer.parseInt(m.group(1));
            String symbol = m.group(2);
            String fileName = m.group(3);
            String lineNum = m.group(4);
            String colNum = m.group(5);

            // mapsInfo 格式为 "filename:line:col"
            String mapsInfo = fileName + ":" + lineNum + ":" + colNum;

            // 尝试解析symbol为地址
            Long address = null;
            try {
                address = Long.parseLong(symbol, 16);
            } catch (NumberFormatException e) {
                // symbol 不是十六进制地址，保持为null
            }

            // addressType 为 HIGH_LEVEL
            AArch64Tombstone.StackDumpInfo.StackFrame frame = new AArch64Tombstone.StackDumpInfo.StackFrame(
                null,  // offsetFromSymbolStart - 高级语言没有偏移
                symbol,
                mapsInfo,
                AArch64Tombstone.StackDumpInfo.StackFrame.AddressType.HIGH_LEVEL,
                address,
                index,
                null  // buildId - 高级语言没有buildId
            );
            return frame;
        }
        return null;
    }

    private AArch64Tombstone.StackDumpInfo.StackFrame parseStackFrame(String line) {
        // 格式: #00 pc 000ef8d4 /system/lib/ld-musl-arm.so.1(__isoc99_vfwscanf+52)(acbcd8a38a05aef9b405c54d21ad6ad5)
        // 解析 index, address, library, symbol, offset, buildId

        // 先提取 index 和 address
        Pattern basicPattern = Pattern.compile("#(\\d+)\\s+pc\\s+([0-9a-fA-F]+)");
        Matcher basicMatcher = basicPattern.matcher(line);
        if (!basicMatcher.find()) {
            return null;
        }

        int index = Integer.parseInt(basicMatcher.group(1));
        String addressStr = basicMatcher.group(2);

        Long address = null;
        try {
            address = Long.parseLong(addressStr, 16);
        } catch (NumberFormatException e) {
            // ignore
        }

        // 提取 library、symbol 和 buildId
        // 格式: /path/to/lib.so(symbol+offset)(buildId)
        // 或者: /path/to/lib.so+offset
        String library = null;
        String symbol = null;
        Long offset = null;
        String buildId = null;

        // 查找 (symbol+offset)(buildId) 部分
        Pattern symbolPattern = Pattern.compile("(/.+?)(?:\\(([^)]+)\\))?(?:\\(([^)]+)\\))?$");
        Matcher symbolMatcher = symbolPattern.matcher(line.substring(basicMatcher.end()));
        if (symbolMatcher.find()) {
            library = symbolMatcher.group(1);
            String symbolInfo = symbolMatcher.group(2);
            buildId = symbolMatcher.group(3);

            // 解析 symbol 和 offset
            if (symbolInfo != null && symbolInfo.contains("+")) {
                String[] parts = symbolInfo.split("\\+");
                symbol = parts[0];
                try {
                    offset = Long.parseLong(parts[1], 16);
                } catch (NumberFormatException e) {
                    // ignore
                }
            } else if (symbolInfo != null) {
                symbol = symbolInfo;
            }

            AArch64Tombstone.StackDumpInfo.StackFrame frame = new AArch64Tombstone.StackDumpInfo.StackFrame(
                offset,
                symbol,
                library,
                AArch64Tombstone.StackDumpInfo.StackFrame.AddressType.ABSOLUTE,
                address,
                index,
                buildId
            );
            return frame;
        }

        return null;
    }

    private AArch64RegisterDumpInfo convertRegisters(Map<String, String> registers) {
        AArch64RegisterDumpInfo info = new AArch64RegisterDumpInfo();

        // ARM64 x0-x29 直接映射
        for (int i = 0; i <= 29; i++) {
            String regName = "x" + i;
            String value = registers.get(regName);
            if (value != null) {
                try {
                    long val = Long.parseLong(value, 16);
                    switch (i) {
                        case 0: info.setX0(val); break;
                        case 1: info.setX1(val); break;
                        case 2: info.setX2(val); break;
                        case 3: info.setX3(val); break;
                        case 4: info.setX4(val); break;
                        case 5: info.setX5(val); break;
                        case 6: info.setX6(val); break;
                        case 7: info.setX7(val); break;
                        case 8: info.setX8(val); break;
                        case 9: info.setX9(val); break;
                        case 10: info.setX10(val); break;
                        case 11: info.setX11(val); break;
                        case 12: info.setX12(val); break;
                        case 13: info.setX13(val); break;
                        case 14: info.setX14(val); break;
                        case 15: info.setX15(val); break;
                        case 16: info.setX16(val); break;
                        case 17: info.setX17(val); break;
                        case 18: info.setX18(val); break;
                        case 19: info.setX19(val); break;
                        case 20: info.setX20(val); break;
                        case 21: info.setX21(val); break;
                        case 22: info.setX22(val); break;
                        case 23: info.setX23(val); break;
                        case 24: info.setX24(val); break;
                        case 25: info.setX25(val); break;
                        case 26: info.setX26(val); break;
                        case 27: info.setX27(val); break;
                        case 28: info.setX28(val); break;
                        case 29: info.setX29(val); break;
                    }
                } catch (NumberFormatException e) {
                    // ignore
                }
            }
        }

        // ARM64 sp
        String spValue = registers.get("sp");
        if (spValue != null) {
            try {
                info.setSp(Long.parseLong(spValue, 16));
            } catch (NumberFormatException e) {
                // ignore
            }
        }

        // ARM64 pc
        String pcValue = registers.get("pc");
        if (pcValue != null) {
            try {
                info.setPc(Long.parseLong(pcValue, 16));
            } catch (NumberFormatException e) {
                // ignore
            }
        }

        return info;
    }

    private AArch64Tombstone.MapsInfo parseMaps(String line) {
        // 格式: bc2000-bc5000 r--p 00000000 /data/local/tmp/libc-test/vfwscanf
        Matcher m = MAPS_PATTERN.matcher(line);
        if (m.find()) {
            try {
                Long start = Long.parseLong(m.group(1), 16);
                Long end = Long.parseLong(m.group(2), 16);
                String permission = m.group(3);
                String name = m.group(5);
                return new AArch64Tombstone.MapsInfo(start, end, permission, name);
            } catch (NumberFormatException e) {
                // ignore
            }
        }
        return null;
    }

    @Override
    public boolean isValid(TroubleEntity entity) {
        return entity != null && entity.getPid() != null;
    }
}
